---
  - name: Stop application
    shell: "{{app_dir}}/stop.sh"
    ignore_errors: yes
  - name: Delete {{ app_dir }}
    file: dest={{ app_dir }} state=absent
  - name: Create {{ app_dir }}
    file: dest={{ app_dir }} mode=755 state=directory
  - name: Create config folder
    file: dest={{ app_dir }}/config mode=755 state=directory
  - name: Create logs folder
    file: dest={{ app_dir }}/logs mode=755 state=directory
  - name: Create tmp folder
    file: dest={{ app_dir }}/tmp mode=755 state=directory
  - name: Copy start.sh, stop.sh, info.sh
    copy: src="./{{item}}" dest={{ app_dir }}
    with_items:
      ['start.sh', 'stop.sh', 'info.sh']
  - name: Copy application.properties
    template: src="../application.properties" dest={{ app_dir }}/config/application.properties
  - name: Copy jar name - "{{ jarName }}"
    copy: src="{{jarName}}" dest={{ app_dir }}
  - name: Set file permissions
    file: dest={{app_dir}}/{{item}} mode=755
    with_items:
      ['start.sh', 'stop.sh', 'info.sh']
  - name: Start application
    shell: "{{app_dir}}/start.sh"

