---
- hosts: kcr
  remote_user: zfall
  tasks:
    - name: Delete file test-be-*.jar
      file: dest={{ app_dir }}/test-be-1.0.0-SNAPSHOT.jar state=absent
    - name: Delete config folder
      file: dest={{ app_dir }}/config state=absent
    - name: Delete logs folder
      file: dest={{ app_dir }}/logs state=absent
    - name: Delete tmp folder
      file: dest={{ app_dir }}/tmp state=absent
    - name: Delete start.sh
      file: dest={{ app_dir }}/start.sh state=absent
    - name: Delete stop.sh
      file: dest={{ app_dir }}/stop.sh state=absent
    - name: Delete info.sh
      file: dest={{ app_dir }}/info.sh state=absent
    - name: Create config folder
      file: dest={{ app_dir }}/config mode=755 state=directory
    - name: Create logs folder
      file: dest={{ app_dir }}/logs mode=755 state=directory
    - name: Create tmp folder
      file: dest={{ app_dir }}/tmp mode=755 state=directory
    - name: Copy start.sh, stop.sh, info.sh
      copy: src="/home/fallz/ansible/test-be/{{item}}" dest={{ app_dir }}
      with_items:
        ['start.sh', 'stop.sh', 'info.sh']
    - name: Copy application.properties
      copy: src="/home/fallz/ansible/test-be/application.properties" dest={{ app_dir }}/config
    - name: Copy test-be-1.0.0-SNAPSHOT.jar
      copy: src="/home/fallz/ansible/test-be/test-be-1.0.0-SNAPSHOT.jar" dest={{ app_dir }}
    - name: Set file permissions
      file: dest={{app_dir}}/{{item}} mode=755
      with_items:
        ['start.sh', 'stop.sh', 'info.sh']
    - name: Start application
      shell: "{{app_dir}}/start.sh"

